#!/bin/bash

if [ -x "$JAVA_HOME/bin/java" ]; then
    JAVA="$JAVA_HOME/bin/java"
else
    JAVA=java
fi

#"${JAVA}" ${JAVA_OPTS} -cp /opt/logstash/ logstash.runner "$@"
"${JAVA}" ${JAVA_OPTS} -jar /opt/logstash/logstash.jar "$@"

exit $?
