#!/bin/bash

# this should be install upgrade or uninstall
MAIN_MENU_ACTION=$1

# this is the location of the desktop file
FILE_NAME=$2


TERMINAL_APP=$(gconftool-2 --get "/desktop/gnome/applications/terminal/exec")
TERMINAL_APP_EXEC_ARG=$(gconftool-2 --get "/desktop/gnome/applications/terminal/exec_arg")

UPGRADE_APP="/usr/sbin/gnome-main-menu-application-upgrade"

if [[ -n $FILE_NAME ]];then
	PACKAGE_SHORT_NAME=$(qfile --quiet --nocolor ${FILE_NAME})
	PACKAGE_LONG_NAME=$(qfile --quiet --nocolor --exact ${FILE_NAME})
fi

cd $HOME

if [[ $MAIN_MENU_ACTION = "upgrade" ]];then

	$(zenity --question --text "Would you like to sync portage first?")
	ANSWER=$?
	$(gksu "${TERMINAL_APP} ${TERMINAL_APP_EXEC_ARG} ${UPGRADE_APP} ${FILE_NAME} ${ANSWER}")

fi

if [[ $MAIN_MENU_ACTION = "uninstall" ]];then
	
	gnome-terminal -e "bash -c 'emerge -Cav =${PACKAGE_LONG_NAME};bash'"

fi

if [[ $MAIN_MENU_ACTION == "install" ]];then

	gnome-terminal -x "bash"

fi

exit 0
