#!/bin/bash

# this is the location of the desktop file
FILE_NAME=$1
RUN_SYNC=$2

DEFAULT_SHELL=$(getent passwd $USER | cut -d ":" -f 7)

if [[ -n $FILE_NAME ]];then
	PACKAGE_SHORT_NAME=$(qfile --quiet --nocolor ${FILE_NAME})
	PACKAGE_LONG_NAME=$(qfile --quiet --nocolor --exact ${FILE_NAME})
fi

cd $HOME

if [[ $RUN_SYNC -eq 0 ]];then
	emerge --sync;
	emerge -uav ${PACKAGE_SHORT_NAME}
elif [[ $RUN_SYNC -eq 1 ]];then
	emerge -uav ${PACKAGE_SHORT_NAME}
fi

# this keeps the shell from exiting
$($DEFAULT_SHELL)

exit 0
